### PR TITLE
feature/step8-footer-section

### PR DESCRIPTION
**Pull request by YanLinGitHub**
- 修正 Bower 及 JavaScript 設定檔
https://github.com/YanLinGitHub/zalora/commit/fe210a95d405b846512416777d39555d21013e23

- 新增 favicon 及 fontAwesome CDN 設定
https://github.com/YanLinGitHub/zalora/commit/5eaa918450e8d0a909be2964fcaf9c01957d76ed

- 調整 SASS 檔 coding stytle（共用檔案）
https://github.com/YanLinGitHub/zalora/commit/afb260f366f6b4bc4c92cb3f3cdd85bdd4159581

- 調整 SASS 檔 coding stytle（section/brand）
https://github.com/YanLinGitHub/zalora/commit/909cebdcebafd95c1f81a81a5149bf440b78f0de

- 新增 footer 內容
https://github.com/YanLinGitHub/zalora/commit/991bc18b67208ace6528b46160b15e06b24dbd6f

### CODE REVIEW

**Comment by YanLinGitHub** [comment]
- 調整 footer 內容
https://github.com/YanLinGitHub/zalora/pull/5/commits/b6cb32ba4f42727cc76f6ab4a7df4b369da8b97d

**Comment by irene84111** [comment]
LGTM

**Comment by irene84111** [comment]
如果確定沒問題的話，麻煩幫我把 WIP 拿掉，我就會 merge 囉

**Comment by YanLinGitHub** [comment]
@irene84111 拿掉 WIP 嘍！感謝

**Pull request merged**
